name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["1.23.x", "1.22.x"]

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.version }}
        cache: true

    - name: Test
      run: go test -race -v ./... -coverpkg=github.com/sysulq/rsmq-go -coverprofile=coverage.out

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5.0.7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
